#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDhTCoCbPCZPS6hqyzF7XhWFc5gRZiYglL85hvMaorxHkAXyV+KtEinwp9jV7adLYCpDY+ZTb8ld1d14LaQkfXVoMpuCIwNJFta0PLzcJwhHKmBgEFDhC5SW985omsIz9dPwQ/WivAq3Q796EHGAwZXk1wYtay/t+ONZdzBAdyVCbnlbMPQgvTfqz3XbcvBxxbXWiMGVFkASmPVnJVTIzPkHBf8npLWK3kiKOfCFVGjZD+fwICsHq8S6s94hLtufEqhm+DEs1Y+1laGuUtvQYPPZ5ozlWeVfad6VQXoe6l+rMevaxvYZWItN/HtfVDGq8WVJmcLH6YsJcfQlVt1IZGfR6CsXHClMRPh41HuJCcrepbY5S5+syfarjMAN3DTdF1kItvJJaCzHKb4Qy7HHTkEPLBIgsfxCWEDLTc+S9297ybAwUWlbYUF8N1UY4jFCThsfuxx47xzauKrwInm6eu7KEiz4hLFP5CsKj8bio/LhsZg17M1n0ewPljaYCsTZ1f9aDj2CtWoQZAXPLgouJmuAnjZ1mDVonCThCaeTsAOiTP0U/lSN92VbyUnDCNUFQP/I6I/SRKK32CBY9dhd0RF9HNRnzutDkdgqa/kn/r8MsLLVNt2t8krvdQ/wPL6kevb/iAPfPGl8TTXIKpw7shdTIIPOYY7WXiGO+wdWWfGSQ== root@wolf-VirtualBox
    lock_passwd: false
    passwd: $6$iuEmTEYehDHJm1kB$o7x4SXniAuc7YBWx69qQDha2w2STpNseZbCRYdkh8TlckKKFO6LlOekJZNO907vw73RWrF8kyJDoWwA0RYC1c1
ssh_pwauth: true
disable_root: true
package_update: true
package_upgrade: true
packages:
  - nginx

runcmd:
  - systemctl start nginx
  - systemctl enable nginx
  - echo "Nginx установлен и запущен через cloud-init" >> /var/log/cloud-init.log

chpasswd:
  expire: false

