---
- name: Prepare and configure webservers
  hosts: webservers
  become: true
  gather_facts: false  # Отключаем сбор фактов, т.к. python может быть не установлен

  pre_tasks:
    - name: Ensure python3 is installed (for Ansible)
      raw: test -e /usr/bin/python3 || (apt update -y && apt install -y python3)
      changed_when: false

    - name: Set Python interpreter explicitly
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Gather facts after ensuring Python is installed
      setup:

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: true
